backend:
  name: git-gateway
  branch: main # Or 'master' if your primary branch is named that
  # Netlify Identity is often used here. If you're using an alternative,
  # like Auth0, you'd configure it here.
  # e.g., name: auth0
  #        domain: YOUR_AUTH0_DOMAIN
  #        client_id: YOUR_AUTH0_CLIENT_ID
  #        app_id: YOUR_AUTH0_APP_ID # if using Auth0 with Decap CMS, this might be required

publish_mode: editorial_workflow # Recommended for client editing: content goes into a "draft" state first
                                # and requires explicit publishing. Remove this line for direct commits.

media_folder: "static/uploads" # Where uploaded images and files will be stored in your Git repo
public_folder: "/uploads"       # The public path to your uploaded images and files (relative to base URL)

collections:
  # ----------------------------------------------------
  # Blog Posts Collection
  # ----------------------------------------------------
  - name: "posts"
    label: "Blog Posts"
    folder: "content/blog" # Adjust this path to where your blog posts are stored
    create: true # Allow users to create new blog posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template (e.g., 2025-06-08-my-first-post.md)
    editor:
      preview: false # Set to true if you want to configure custom previews
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true, format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: true}
      - {label: "Author", name: "author", widget: "string", default: "Your Name"}
      - {label: "Featured Image", name: "image", widget: "image", required: false, allow_multiple: false, choose_url: false}
      - {label: "Image Alt Text", name: "image_alt", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["Uncategorized"], required: false, field: {label: "Category", name: "category", widget: "string"}}
      - {label: "Tags", name: "tags", widget: "list", required: false, field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: true, hint: "Set to false to publish the post"}

 # ----------------------------------------------------
  # Pages Collection (e.g., About, Contact, etc.)
  # ----------------------------------------------------
  - name: "pages"
    label: "Pages"
    folder: "content/pages" # Adjust this path to where your static pages are stored
    create: true            # <--- THIS IS LINE 45 IN THE EXAMPLE
    slug: "{{slug}}"        # Filename template (e.g., about.md, contact.md)
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", hint: "The URL path for this page (e.g., /about/, /contact/)", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: true, hint: "Set to false to publish the page"}
