backend:
  name: git-gateway
  branch: main   # or whichever branch you're using

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page Content", name: "body", widget: "code", default: "", required: false }
