backend:
  name: git-gateway
  branch: main   # or whichever branch you're using

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: ""            # root folder if editing HTML directly
    create: false         # set true if you want to add new pages
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
