backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "src"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "services"
    label: "Services"
    folder: "src/services"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }